name: Appium Android

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    env:
      ANDROID_HOME: C:\Android\sdk
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Install Android SDK
      uses: android-actions/setup-android@v3
      with:
        android-sdk-root: ${{ env.ANDROID_HOME }}
        cmdline-tools: 'latest'
        build-tools: '34.0.0'
        platforms: 'android-34'
        emulator: true

    - name: Configure JAXB environment
      run: |
        New-Item -ItemType Directory -Path jaxb_libs -Force

        $jaxbLibs = @(
          "https://repo1.maven.org/maven2/javax/xml/bind/jaxb-api/2.3.1/jaxb-api-2.3.1.jar",
          "https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-core/2.3.0.1/jaxb-core-2.3.0.1.jar",
          "https://repo1.maven.org/maven2/com/sun/xml/bind/jaxb-impl/2.3.1/jaxb-impl-2.3.1.jar",
          "https://repo1.maven.org/maven2/javax/activation/activation/1.1.1/activation-1.1.1.jar"
        )
        
        foreach ($lib in $jaxbLibs) {
          $fileName = $lib.Split('/')[-1]
          Invoke-WebRequest -Uri $lib -OutFile "jaxb_libs\$fileName"
        }

        $wrapperScript = @'
        @echo off
        setlocal
        set CLASSPATH=%~dp0jaxb_libs\*;%CLASSPATH%
        set JAVA_OPTS=--add-modules java.xml.bind %JAVA_OPTS%
        "%ANDROID_HOME%\cmdline-tools\latest\bin\sdkmanager" %*
        endlocal
        '@
        $wrapperScript | Out-File -FilePath "$env:GITHUB_WORKSPACE\sdkmanager.bat" -Encoding ASCII

    - name: Accept licenses
      run: |
        mkdir -p "$env:ANDROID_HOME/licenses"
        echo "8933bad161af4178b1185d1a37fbf41ea5269c55" > "$env:ANDROID_HOME/licenses/android-sdk-license"
        echo "d56f5187479451eabf01fb78af6dfcb131a6481e" >> "$env:ANDROID_HOME/licenses/android-sdk-license"

    - name: Install system image
      run: |
        .\sdkmanager.bat --install "system-images;android-34;google_apis;x86_64"
        .\sdkmanager.bat --list

    - name: Create AVD
      run: |
        avdmanager create avd -n test -k "system-images;android-34;google_apis;x86_64" -d pixel_4 -f

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium
      run: |
        npm install -g appium@2.0
        npm install -g appium-doctor
        appium-doctor --android

    - name: Start Appium server
      run: |
        Start-Process -FilePath "appium" -ArgumentList "--relaxed-security","--log-level","debug" -WindowStyle Hidden
        Start-Sleep -Seconds 15

    - name: Start emulator
      run: |
        Start-Process -FilePath "$env:ANDROID_HOME\emulator\emulator" -ArgumentList "-avd","test","-no-window","-gpu","swiftshader_indirect" -WindowStyle Hidden
        adb wait-for-device
        while (-not ((adb shell getprop sys.boot_completed) -eq "1")) {
          Start-Sleep -Seconds 5
          Write-Host "Waiting for emulator..."
        }

    - name: Run tests
      run: |
        mvn clean test -Pandroid -Dappium.server.url=http://127.0.0.1:4723

    - name: Upload reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/screenshots/
