name: Appium Android
on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        api-level: [25]  
        target: [default]
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'corretto'
    - uses: actions/setup-node@v2
      with:
        node-version: '12'
    - run: |
        npm install -g appium@v1.20.2  # Ou considere uma versão mais recente, se necessário
        appium -v
        nohup appium &>/dev/null &  # Usando nohup para garantir que o Appium continue em segundo plano
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test -Pandroid
