name: Appium Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        api-level: [34]  
        target: [default]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 (AdoptOpenJDK)
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adoptopenjdk'
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
    - run: |
        npm install -g appium@1.20.2  # Instalar a versão específica do Appium
        appium -v  # Verificar a versão do Appium
        nohup appium &>/dev/null &  # Iniciar o Appium em segundo plano
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: mvn clean test -P android
