name: Appium Android

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest 
    strategy:
      matrix:
        api-level: [34]  
        target: [default]
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'
    - uses: actions/setup-node@v3
      with:
        node-version: '12'
    - run: |
        npm install -g appium@1.20.2
        appium -v
        nohup appium &>/dev/null &
    - name: List files (debug)
      run: ls -la
    - name: Run Appium Tests
      uses: reactivecircus/android-emulator-runner@v2.1.0
      with:
        api-level: ${{ matrix.api-level }}
        target: ${{ matrix.target }}
        arch: x86_64
        profile: Nexus 6
        script: |
          # Reset ADB e aguarda o device
          adb kill-server
          adb start-server
          adb wait-for-device
          
          until adb shell getprop sys.boot_completed | grep -q "1"; do
            sleep 5
          done
      
          mvn clean test -Pandroid
