name: Appium Android (Windows)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3
      with:
        android-sdk-root: C:\Android\android-sdk

    - name: Add Android tools to PATH
      run: |
        echo "C:\Android\android-sdk\emulator" >> $env:GITHUB_PATH
        echo "C:\Android\android-sdk\cmd" >> $env:GITHUB_PATH
        echo "C:\Android\android-sdk\platform-tools" >> $env:GITHUB_PATH

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install Appium
      run: |
        npm install -g appium@2.0
        npm install -g appium-doctor
        appium-doctor --android

    - name: Start Appium server
      run: |
        Start-Process -FilePath "appium" -ArgumentList "--relaxed-security","--log-timestamp","--local-timezone" -WindowStyle Hidden
        Start-Sleep -Seconds 10

    - name: Set up Android Emulator
      run: |
        # Install HAXM
        choco install -y haxm --force

        # Accept licenses
        yes | sdkmanager --licenses

        # Install system image
        sdkmanager "system-images;android-34;google_apis;x86_64"

        # Create AVD
        avdmanager create avd -n test_avd -k "system-images;android-34;google_apis;x86_64" -d pixel_4 -f

        # Verify emulator path
        where.exe emulator

        # Start emulator with full path
        $emulatorPath = "$env:ANDROID_HOME\emulator\emulator.exe"
        Start-Process -FilePath $emulatorPath -ArgumentList "-avd","test_avd","-no-window","-gpu","swiftshader_indirect" -WindowStyle Hidden

        # Wait for device
        adb wait-for-device
        while (-not ((adb shell getprop sys.boot_completed) -eq "1")) {
          Start-Sleep -Seconds 5
          Write-Host "Waiting for device..."
        }

    - name: Run Tests
      run: |
        mvn clean test -Pandroid -Dappium.server.url=http://127.0.0.1:4723

    - name: Upload test reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-reports
        path: |
          target/surefire-reports/
          target/screenshots/
